name: Update Manifest
on:
  workflow_dispatch:
  push:
    paths:
      - 'ManifestUpdater/Resources/internal_manifest.json'
  # Every 120 minutes, since RT modding is ded. This should be safe, GitHub limit is 1000 / hour and Nexus is 500 / hour.
  schedule:
  - cron: "0/120 * * * *"
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEXUS_APITOKEN: ${{ secrets.NEXUS_APITOKEN }}
jobs:

  build:
    runs-on: windows-latest
    steps:

    - name: Checkout GitHub actions
      uses: actions/checkout@v3
    - name: .NET Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Run Updater
      run: dotnet run --project ./ManifestUpdater 
